### ISSUE TITLE
HEROKU 배포

### ISSUE THREAD

**Issue by gomjellie** [woowa-techcamp-2021/baemin-13#47]
완성도 낮더라도 배포 어떻게든 해야된다.

**Comment by 0woodev** [comment]
1차 배포는 몇가지 기능이 누락된 채로 배포를 했습니다.

누락된 기능 
- [ ] 로그인 연동

**Comment by gomjellie** [comment]
이거 닫아도 될까요?

**Comment by gomjellie** [comment]
인메모리 디비로 해결!

**Comment by 0woodev** [comment]
가장 최근버젼으로 업로드한 후에 닫으면 될것 같습니다!

**Comment by gomjellie** [comment]
dev 브랜치 최신버전으로 배포하고, dev브랜치 업데이트 될때마다 헤로쿠 자동배포되게 설정했습니다
